# Generated by Django 4.2.10 on 2024-04-23 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuracion',
            name='valor',
            field=models.CharField(max_length=200),
        ),
    ]
