#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd legalbot/app

python manage.py check --deploy

python manage.py loaddata ui/config/config.json
python manage.py collectstatic --noinput 
python manage.py createsuperuser --noinput
python manage.py migrate
gunicorn --config gunicorn_config.py config.wsgi:application

cd ..
