#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

cd legalbot/app

python manage.py check --deploy

python manage.py collectstatic --noinput

python manage.py makemigrations
python manage.py migrate
python manage.py loaddata ui/fixtures/config.json 
# python manage.py createsuperuser --noinput
gunicorn --config gunicorn_config.py config.wsgi:application
#python manage.py runserver 0.0.0.0:8000
cd ..
